### ISSUE TITLE
[404 NOT FOUND] Gives 404 not found when tried to use

### ISSUE THREAD

**Issue by naveen-kumar-vadla** [marchbold/copy-release-to-repository-action#1]
I tried to use this github action in my pipeline by configuring like below.
```  copy-release:
    runs-on: ubuntu-latest
    needs: releases-matrix
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy release to another repository
        uses: marchbold/copy-release-to-repository-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          destination_repo: 'MY_ORGANISAION/MY_REPONAME'
```

And it is giving 404 not found error attached the logs below. 
```
airsdk
airsdkmanager
RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/marchbold/copy-release-to-repository-action/v1/dist/index.js:2155:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestWithGraphqlErrorHandling (/home/runner/work/_actions/marchbold/copy-release-to-repository-action/v1/dist/index.js:4407:20)
    at async Job.doExecute (/home/runner/work/_actions/marchbold/copy-release-to-repository-action/v1/dist/index.js:5112:18) {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/airsdk/airsdkmanager/releases/tags/v0.1.6-test',
    status: 404,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 22 Jul 2024 14:48:25 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'github.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-github-permissions': 'contents=read',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '5C01:149D17:B32D354:B512BF4:669E7139',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4975',
      'x-ratelimit-reset': '1721663290',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '25',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest/releases/releases#get-a-release-by-tag-name',
      status: '404'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/airsdk/airsdkmanager/releases/tags/v0.1.6-test',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.6.0 Node.js/20.13.1 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }
}
```

It is happening because of hard coded value for the source repo name at this line https://github.com/marchbold/copy-release-to-repository-action/blob/main/lib/index.js#L50

Please change it to take source name from environment variable. I guess, uncommenting the commented code might be a solution.

**Comment by marchbold** [comment]
Thanks for pointing this out. 

Currently this was only designed to be used in our specific case but I'll make some changes to ensure it's available for general usage.
